language: cpp

sudo: required

branches:
    only:
      - master

env:
  - BUILD_TYPE=release

cache:
    apt: true
    directories:
      - /opt/qt512/
              
before_install:
  - source .travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - source .travis/${TRAVIS_OS_NAME}/install.sh
    
script:
  - source .travis/${TRAVIS_OS_NAME}/building.sh
  
jobs:
    include:
      - stage: "Build"
        os: linux
        dist: xenial
        compiler: clang
      - compiler: gcc
          
      - stage: "Post-Build"
        os: linux
        dist: xenial
        sudo: required
        compiler: gcc
        env: BUILD_TYPE=coverage
        services: xvfb
        script:
          - source .travis/${TRAVIS_OS_NAME}/building.sh
          - source .travis/${TRAVIS_OS_NAME}/coverage.sh        
      - env: BUILD_TYPE=doxygen
        services:
        branches:
            only:
              - master
        script:
          - source .travis/${TRAVIS_OS_NAME}/doxygen.sh
          