language: cpp

sudo: required

branches:
    only:
      - master
      - travis-windows-tests

stages:
  - name: "Building"
  - post-build
    if: branch = master

env:
  - BUILD_TYPE=release
              
before_install:
  - source .travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - source .travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - source version.sh

script:
  - source .travis/${TRAVIS_OS_NAME}/building.sh
  - source .travis/${TRAVIS_OS_NAME}/testing.sh
  - source .travis/${TRAVIS_OS_NAME}/viewer_building.sh

jobs:
    include:
      - stage: "Building"
        name: "Windows build with GCC"
        os: windows
        compiler: gcc
