language: cpp

sudo: required

branches:
    only:
      - master
      - travis-windows-tests

env:
  - BUILD_TYPE=release
              
before_install:
  - source .travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - source .travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - source version.sh

script:
  - source .travis/${TRAVIS_OS_NAME}/building.sh

jobs:
    include:
      - stage: "Build"
        name: "Windows build with GCC"
        os: windows
        compiler: gcc
      - name: "Linux build with Clang"
        os: linux
        dist: xenial
        compiler: clang
      - name: "Linux build with GCC"
        os: linux
        dist: xenial 
        compiler: gcc
